[package]
name = "distantland_texture"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
fast_image_resize.workspace = true
hashbrown.workspace = true
image.workspace = true
image_dds.workspace = true
intel_tex_2.workspace = true
rayon.workspace = true
rkyv.workspace = true
serde.workspace = true
tracing.workspace = true

[lints]
workspace = true
